# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1

# Rename this file to languages.toml to enable multilingual support
[zh-tw]
languageName = "繁體中文"
languagedirection = "ltr"
title = "範例網站"
weight = 1
